FROM ubuntu:20.04

# Set environment variables to configure non-interactive installation
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y --no-install-recommends \
    wine unzip && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN dpkg --add-architecture i386 && \
    apt update && \
    apt install -y wine32 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*

# RUN useradd -m dockeruser
# USER dockeruser
WORKDIR /app
RUN mkdir files
COPY code_smaller.zip /app/files
COPY vcruntime140_1.dll ~/.wine/drive_c/windows/system32/

# COPY start.sh /start.sh
# RUN chmod +x /start.sh

# ENTRYPOINT ["/start.sh"]
ENTRYPOINT ["/bin/bash"]


# RUN apt update && \
#     apt install wine32 && \
#     apt install winetricks

# RUN winetricks vcrun2019



# RUN dpkg --add-architecture i386 && \
#     apt-get update && \
#     apt-get install -y --no-install-recommends \
#     wine wine64 wine32 winetricks xvfb unzip && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# RUN apt-get update && apt-get install -y wine32



