apiVersion: apps/v1
kind: Deployment
metadata:
  name: arp-server
  namespace: horcrux
  labels:
    app: arp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arp-server
  template:
    metadata:
      labels:
        app: arp-server
    spec:
      imagePullSecrets:
        - name: nhn-registry-secret  
      containers:
      - name: horcrux-server
        imagePullPolicy: IfNotPresent
        image: 923eb773-kr1-registry.container.nhncloud.com/uragan-container-registry/horcrux@sha256:8405755f2b5a9bff59566166644b31fd1fe2c32716c74afceea3fcb49518dc0c
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "2560Mi"
            cpu: "1000m"
          limits:
            memory: "4584Mi"
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30