apiVersion: v1
kind: Service
metadata:
  namespace: horcrux
  name: arp-service
  labels:
    app: arp-service
spec:
  selector:
    app: arp-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer